<a href="https://colab.research.google.com/github/Kkartik14/Kkartik14/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Vector -> data point and can have number of dimensions
TENSOR-> main object passed around and manipulated, each tensor has a data type and a shape(representation of dimensions of tensor).

Creating tensors

In [ ]:
string = tf.Variable("this",tf.string)
num = tf.Variable(1,tf.int64)

Rank/Degree of Tensors

Number of dimensions involved in the tensor. Tensor of rank 0 is called scaler
When we have an array it is automatically atleast rank 1


In [ ]:
tensor_1= tf.Variable(["Test"], tf.string)
tensor_2 = tf.Variable([["test","ok"],["test","yes"]],tf.string)
tensor_3 = tf.Variable([[["test","ok","one"],["test","ok","one"]],[["test","ok","one"],["test","ok","one"]]],tf.string)

method to determine rank of the tensor

In [ ]:
tf.rank(tensor_2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tensor_3.shape

TensorShape([2, 2, 3])

Changing the shapes using tf.reshape() method


In [ ]:
tensor = tf.ones([1,2,3])
tensor1 = tf.reshape(tensor, [2,3,1])
tensor2 = tf.reshape(tensor, [2,-1])
print(tensor)
print(tensor1)
print(tensor2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


Different kinds of tensors


*   Variables
*   Constants
*   PlaceHolders
*   SparseTensor

In [ ]:
pip install numpy pandas